/**
 * Generates the plugin-wiring files from the ENABLE_PLUGINS env var.
 *
 * Runs automatically before dev/build (npm pre-hooks). It writes two small
 * generated files that core imports:
 *   - src/lib/extensions/active-plugins.js  (frontend registration)
 *   - worker/src/active-plugins.js          (backend routes)
 *
 * When ENABLE_PLUGINS=1 AND the private plugin files exist, the generated
 * files re-export the real plugins. Otherwise they export no-op stubs, so the
 * build has no optional plugins wired in.
 *
 * Both generated files are gitignored.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * Resolve a var from the process env, then from local env files (npm pre-hooks
 * don't auto-load .env files, so we read them ourselves).
 * @param {string} name
 */
const readEnv = (name) => {
	if (process.env[name] !== undefined) return process.env[name];
	for (const file of ['.env.local', '.env.development', '.env']) {
		const p = join(root, file);
		if (!existsSync(p)) continue;
		const line = readFileSync(p, 'utf8')
			.split(/\r?\n/)
			.find((l) => l.trim().startsWith(`${name}=`));
		if (line) return line.slice(line.indexOf('=') + 1).trim();
	}
	return undefined;
};

const frontendReal = join(root, 'src/lib/extensions/plugins/register.js');
const backendReal = join(root, 'worker/src/plugins/routes.js');

const wanted = readEnv('ENABLE_PLUGINS') === '1';
const on = wanted && existsSync(frontendReal) && existsSync(backendReal);

if (wanted && !on) {
	console.warn('[wire-plugins] ENABLE_PLUGINS=1 but plugin files are missing — building without plugins.');
}

const banner = '// AUTO-GENERATED by scripts/wire-plugins.mjs — do not edit. Toggle with ENABLE_PLUGINS.\n';

writeFileSync(
	join(root, 'src/lib/extensions/active-plugins.js'),
	banner + (on
		? "export { registerPlugins } from './plugins/register.js';\n"
		: 'export const registerPlugins = () => {};\n')
);

writeFileSync(
	join(root, 'worker/src/active-plugins.js'),
	banner + (on
		? "export { pluginRoutes } from './plugins/routes.js';\n"
		: 'export const pluginRoutes = [];\n')
);

console.log(`[wire-plugins] plugins ${on ? 'ENABLED' : 'disabled'}`);
